# -*- coding: utf-8 -*-
"""Text_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rfLgx38Lus6yNkjiTTAj9ZoXSMl2pITk

###**Step 1 — Verify Your PDF Type**

Your analysis: The PDF has text that is selectable, which means it is a digital PDF.

*   We can use `pdfplumber` here.
*   *Note*: If it was a scanned PDF, we would have to use OCR to extract text from images.
"""

pip install pdfplumber

"""###**Step 2 — Extract Text from One Page (Test First)**"""

import pdfplumber

pdf_path = "/content/iesc107.pdf"

with pdfplumber.open(pdf_path) as pdf:
    first_page = pdf.pages[0]
    text = first_page.extract_text()

print(text)

"""#### Output Preview
```
7
C
hapter
MMMMM
OOOOOTTTTTIIIIIOOOOONNNNN
In everyday life, we see some objects at rest Activity ______________7.1
and others in motion. Birds fly, fish swim,
blood flows through veins and arteries, and
cars move. Atoms, molecules, planets, stars
...
Reprint 2025-26
```

#### Analysis of Layout Distortion
*   **Issue**: Layout distortion caused by how the PDF stores text (especially headings and spaced lettering like M O T I O N).
*   **Reason**: This happens because:
    *   Text is stored character-by-character with spacing.
    *   Headings use letter spacing / stylized fonts.
    *   `pdfplumber.extract_text()` reconstructs it imperfectly.

### **Step 3 — Fix Text Extraction (Use Better Settings)**

*   **Goal**: Modify extraction with layout tuning.
"""

pdf_path = "/content/iesc107.pdf"

with pdfplumber.open(pdf_path) as pdf:
    first_page = pdf.pages[0]

    text = first_page.extract_text(
        x_tolerance=2,
        y_tolerance=2
    )

print(text)

"""#### Why `x_tolerance` and `y_tolerance` Help:
*   `x_tolerance` → controls horizontal merging of characters.
*   `y_tolerance` → controls line grouping.

### **Step 4 — Remove Repeated Characters (Critical Cleanup)**

*   **Goal**: Fix things like:
    ```
    MMMMM
    OOOOOTTTTTIIIIIOOOOONNNNN
    ```
"""

import re

def fix_repeated_chars(text):
    # Replace repeated characters (more than 2 times) with single
    return re.sub(r'(.)\1{2,}', r'\1', text)

text = fix_repeated_chars(text)

text

"""### **Step 5 — Fix Broken Words Like "C hapter"**

*   **Issue**: It's not just repeated characters; it's line fragmentation due to PDF layout blocks.
*   **Specifically**:
    *   `"C\nhapter"` → characters split across lines.
    *   `"M\nOTION"` → heading broken vertically.
    *   Sentences merging incorrectly across columns.
*   **Conclusion**: This is a layout reconstruction problem, not just simple cleaning.
"""

def fix_spaced_words(text):
    # Join single characters separated by spaces (e.g., "C h a p t e r")
    return re.sub(r'\b(?:[A-Za-z]\s){2,}[A-Za-z]\b',
                  lambda m: m.group(0).replace(" ", ""),
                  text)

print(fix_spaced_words(text))

def fix_heading_lines(text):
    lines = text.split("\n")
    fixed_lines = []
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        # Case 1: Chapter number + broken "Chapter"
        if (
            i + 2 < len(lines)
            and lines[i].strip().isdigit()
            and lines[i+1].strip().lower() in ["c", "ch"]
            and re.match(r"hapter", lines[i+2].strip(), re.IGNORECASE)
        ):
            chapter_num = lines[i].strip()
            fixed_lines.append(f"Chapter {chapter_num}")
            i += 3
            continue

        # Case 2: Broken ALL CAPS word like M + OTION
        if (
            i + 1 < len(lines)
            and len(lines[i].strip()) == 1
            and lines[i].strip().isalpha()
            and lines[i+1].strip().isalpha()
        ):
            combined = lines[i].strip() + lines[i+1].strip()
            fixed_lines.append(combined)
            i += 2
            continue

        # Default: keep line
        fixed_lines.append(line)
        i += 1

    return "\n".join(fixed_lines)

print(fix_heading_lines(text))

"""### **Step 6 — Combine Into Clean Pipeline**"""

import pdfplumber
import re

def fix_repeated_chars(text):
    return re.sub(r'(.)\1{2,}', r'\1', text)

def fix_spaced_words(text):
    return re.sub(r'\b(?:[A-Za-z]\s){2,}[A-Za-z]\b',
                  lambda m: m.group(0).replace(" ", ""),
                  text)

def fix_heading_lines(text):
    lines = text.split("\n")
    fixed_lines = []
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        # Case 1: Chapter number + broken "Chapter"
        if (
            i + 2 < len(lines)
            and lines[i].strip().isdigit()
            and lines[i+1].strip().lower() in ["c", "ch"]
            and re.match(r"hapter", lines[i+2].strip(), re.IGNORECASE)
        ):
            chapter_num = lines[i].strip()
            fixed_lines.append(f"Chapter {chapter_num}")
            i += 3
            continue

        # Case 2: Broken ALL CAPS word like M + OTION
        if (
            i + 1 < len(lines)
            and len(lines[i].strip()) == 1
            and lines[i].strip().isalpha()
            and lines[i+1].strip().isalpha()
        ):
            combined = lines[i].strip() + lines[i+1].strip()
            fixed_lines.append(combined)
            i += 2
            continue

        # Default: keep line
        fixed_lines.append(line)
        i += 1

    return "\n".join(fixed_lines)

def extract_clean_text(pdf_path):
    all_text = ""

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text(x_tolerance=2, y_tolerance=2)

            if text:
                text = fix_repeated_chars(text)
                text = fix_spaced_words(text)
                text = fix_heading_lines(text) # Apply the heading fix
                all_text += text + "\n"

    return all_text

cleaned_text = extract_clean_text(pdf_path)
print(cleaned_text)

"""### Gaps in Text Extraction

*   Activity sections are not distinctly separated.
*   'Think and Act' sections lack clear demarcation.
*   The main text of the chapter is not well-organized.
*   Lack of image data or proper handling for it.
*   Presence of irrelevant text data, such as 'Reprint 2025-26'.
*   Questions are mixed with informational text.
*   Table data is not organized or extracted properly.
*   Formulas lack consistent structure or clear representation.
"""

